const myProducts = [
    // קטגוריית בסיס
   { category: 'base', name: 'דגם 1', image: 'base1.png', price: 9500 },
  { category: 'base', name: 'דגם 2', image: 'base2.png', price: 9500 },
  { category: 'base', name: 'דגם 3', image: 'base3.png', price: 9500 },
  { category: 'base', name: 'דגם 4', image: 'base4.png', price: 9500 },
  { category: 'base', name: 'דגם 5', image: 'base5.png', price: 9500 },
  { category: 'base', name: 'דגם 6', image: 'base6.png', price: 9500 },
  { category: 'base', name: 'דגם 7', image: 'base7.png', price: 9500 },
  { category: 'base', name: 'דגם 8', image: 'base8.png', price: 9500 },
  { category: 'base', name: 'דגם 9', image: 'base9.png', price: 9500 },
  { category: 'base', name: 'דגם 10', image: 'base10.png', price: 9500 },
  { category: 'base', name: 'דגם 11', image: 'base11.png', price: 9500 },
  { category: 'base', name: 'דגם 12', image: 'base12.png', price: 9500 },
  { category: 'base', name: 'דגם 13', image: 'base13.png', price: 9500 },
  { category: 'base', name: 'דגם 14', image: 'base14.png', price: 9500 },
  { category: 'base', name: 'דגם 15', image: 'base15.png', price: 9500 },
  { category: 'base', name: 'דגם 16', image: 'base16.png', price: 9500 },
    // קטגוריית משרביה
 { category: 'mashrabiya', name: 'משרביה דגם 1', image: 'mash1.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 2', image: 'mash2.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 3', image: 'mash3.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 4', image: 'mash4.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 5', image: 'mash5.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 6', image: 'mash6.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 7', image: 'mash7.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 8', image: 'mash8.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 9', image: 'mash9.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 10', image: 'mash10.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 11', image: 'mash11.png', price: 0 },
  { category: 'mashrabiya', name: 'משרביה דגם 12', image: 'mash12.png', price: 0 },

    // קטגוריית תאורה

  { category: 'profile', name: 'לד דגם 1', image: 'led1.png', price: 100 },
  { category: 'profile', name: 'לד דגם 2', image: 'led2.png', price: 100 },
  { category: 'profile', name: 'לד דגם 3', image: 'led3.png', price: 100 },
  { category: 'profile', name: 'לד דגם 4', image: 'led4.png', price: 100 },
  { category: 'profile', name: 'לד דגם 5', image: 'led5.png', price: 100 },
  { category: 'profile', name: 'לד דגם 6', image: 'led6.png', price: 100 },
  { category: 'profile', name: 'לד דגם 7', image: 'led7.png', price: 100 },
  { category: 'profile', name: 'לד דגם 8', image: 'led8.png', price: 100 },
  { category: 'profile', name: 'לד דגם 9', image: 'led9.png', price: 100 },
  { category: 'profile', name: 'לד דגם 10', image: 'led10.png', price: 100 },
  { category: 'profile', name: 'לד דגם 11', image: 'led11.png', price: 100 },
  { category: 'profile', name: 'לד דגם 12', image: 'led12.png', price: 100 },
  { category: 'profile', name: 'לד דגם 13', image: 'led13.png', price: 100 },
  { category: 'profile', name: 'לד דגם 14', image: 'led14.png', price: 100 },
  { category: 'profile', name: 'לד דגם 15', image: 'led15.png', price: 100 },
];
